### ISSUE TITLE
shouldn't (series::install) be wrapped by eval-when ?

### ISSUE THREAD

**Issue by avodonosov** [jwiegley/periods#8]
The `(series::install)` called in the periods.lisp modifies the current *package*, 
shadowing the `let let* multiple-value-bind funcall defun` symbols and providing series-specific versions instead.

Shouldn't it happen during compile-time too?

**Comment by christophejunke** [comment]
It seems to me that there was no need to call series::install (see 2473b38337bbd115389c598d062848ba64e9e783).
